# Generated by Django 3.2.9 on 2021-12-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostID', models.CharField(max_length=32)),
                ('AccountName', models.CharField(max_length=32)),
            ],
        ),
    ]
