# Generated by Django 3.2.9 on 2021-12-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegionSearch', '0003_auto_20211225_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='Place',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
