# Generated by Django 3.2.9 on 2021-12-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegionSearch', '0004_total_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='total',
            new_name='posts',
        ),
    ]
