# Generated by Django 3.2.9 on 2021-12-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegionSearch', '0005_rename_total_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='total',
        ),
    ]
