# Generated by Django 3.2.9 on 2021-12-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegionSearch', '0006_rename_posts_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='PictureUrl',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
